#lang racket

; Quicksort for hash tables using only lambda functions
; Sorts by a given key
(((lambda (sort)
    (lambda (lst key)
      (sort sort lst key)))
  (lambda (self lst key)
    ((lambda (len)
       ((lambda (continue)
          (continue len lst key))
        (lambda (len lst key)
          (if (<= len 1)
              lst
              ((lambda (pivot rest)
                 ((lambda (pivot-val)
                    ((lambda (left right)
                       (append (self self left key) 
                               (cons pivot (self self right key))))
                     ((lambda (filter-left)
                        (filter-left filter-left rest 
                          (lambda (x) 
                            (< (hash-ref x key) pivot-val))))
                      (lambda (self lst pred)
                        (if (null? lst)
                            '()
                            (if (pred (car lst))
                                (cons (car lst) (self self (cdr lst) pred))
                                (self self (cdr lst) pred)))))
                     ((lambda (filter-right)
                        (filter-right filter-right rest 
                          (lambda (x) 
                            (>= (hash-ref x key) pivot-val))))
                      (lambda (self lst pred)
                        (if (null? lst)
                            '()
                            (if (pred (car lst))
                                (cons (car lst) (self self (cdr lst) pred))
                                (self self (cdr lst) pred)))))))
                  (hash-ref pivot key)))
               (car lst)
               (cdr lst))))))
     (length lst))))
 (list (hash 'name "John" 'age 30)
       (hash 'name "Alice" 'age 25)
       (hash 'name "Bob" 'age 35)
       (hash 'name "Charlie" 'age 20))
 'age)